name: Build & Check

on: push

jobs:
  detektAll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: ./.github/actions/gradle-setup-action
      - run: ./gradlew detektAll

  verifyVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: ./.github/actions/gradle-setup-action
      - run: ./gradlew verifyVersion

  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: ./.github/actions/gradle-setup-action
      - run: ./gradlew assemble

  check:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: ./.github/actions/gradle-setup-action
      - run: ./gradlew check
